#!/bin/bash

MONGO_CONTAINER_KEYFILE=$1
ROUTER_PORT=$2
CONFIG_RS_NAME=$3
CONFIG_SERVER_NAME=$4
CONFIG_SERVER_PORT=$5
CONFIG_RS_COUNT=$6

echo "DEBUG: MONGO_CONTAINER_KEYFILE  = $MONGO_CONTAINER_KEYFILE"
echo "DEBUG: ROUTER_PORT              = $ROUTER_PORT"
echo "DEBUG: CONFIG_RS_NAME           = $CONFIG_RS_NAME"
echo "DEBUG: CONFIG_SERVER_NAME       = $CONFIG_SERVER_NAME"
echo "DEBUG: CONFIG_SERVER_PORT       = $CONFIG_SERVER_PORT"
echo "DEBUG: CONFIG_RS_COUNT          = $CONFIG_RS_COUNT"

CONFIG_STR=""
for i in $(seq 1 $CONFIG_RS_COUNT); do 
  if [ $i -eq 1 ]; then # empty string
    CONFIG_STR="${CONFIG_SERVER_NAME}_$i:$CONFIG_SERVER_PORT"
  else
    CONFIG_STR="$CONFIG_STR,${CONFIG_SERVER_NAME}_$i:$CONFIG_SERVER_PORT"
  fi
done

mongos --port $ROUTER_PORT --configdb config-svr/$CONFIG_STR --bind_ip_all --keyFile $MONGO_CONTAINER_KEYFILE
